services:
#    xxam_core.example:
#        class: Xxam\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


#every portal-widget must start with "xxamportalwidget...."
    xxamportalwidget.core.feed:
        class: Xxam\CoreBundle\Controller\FeedWidgetController
        arguments: ["@templating"]
        tags:
            -  { name: xxamportalwidget }
            
    
        
        
            
    kernel.listener.tenantsetparameter:    
       class: Xxam\CoreBundle\EventListener\TenantSetParameter
       arguments: [ @service_container, @doctrine.orm.entity_manager ]
       tags:
           - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 20 }
           
    kernel.listener.command_tenantsetparameter:    
       class: Xxam\CoreBundle\EventListener\TenantSetParameter
       arguments: [ @service_container, @doctrine.orm.entity_manager ]
       tags:
           - { name: kernel.event_listener, event: console.command, method: onCommand, priority: 20 }
           
    tenant.listener:
        class: Xxam\CoreBundle\EventListener\TenantSetter
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            
            
#    xxam_bit_ratchet_server:
#        class: Xxam\CoreBundle\Services\XxamServerService
#        arguments:
#          websocket:
#            host: %bit_ratchet.websocket.host%
#            port: %bit_ratchet.websocket.port%
#          listeners: %bit_ratchet.listeners%
#          logger: @logger
#        tags:
#            - { name: monolog.logger, channel: ratchet_server }