Xxam\CmsAdminBundle\Document\Page:
    uri_schema: /{title}
    token_providers:
        title: [content_method, { method: getTitle }]

Xxam\CmsAdminBundle\Document\Post:
    uri_schema: /post/{date}/{title}
    token_providers:
        date: [content_datetime, { method: getDate }]
        title: [content_method, { method: getTitle }]


