






fos_user_security_login:
    #path: /login
    #defaults: { _controller: XxamUserBundle:Security:login }
    #methods: [ GET ]
    resource: "@XxamUserBundle/Controller/SecurityController.php"
    type: annotation

fos_user_security_check:
    defaults: { _controller: FOSUserBundle:Security:check }
    methods: [ POST ]
    path: "/login_check"

fos_user_security_logout:
    defaults: { _controller: FOSUserBundle:Security:logout }
    methods: [ GET ]
    path: "/logout"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: "/profile"

fos_user_registration:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: "/register"

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: "/resetting"

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: "/profile"


user:
    resource: "@XxamUserBundle/Controller/UserController.php"
    type: annotation

xxam_user_user_api:
    resource: "@XxamUserBundle/Controller/UserRESTController.php"
    type:   rest
    prefix:   /api
    
group:
    resource: "@XxamUserBundle/Controller/GroupController.php"
    type: annotation
    
xxam_user_group_api:
    resource: "@XxamUserBundle/Controller/GroupRESTController.php"
    type:   rest
    prefix:   /api