<?php

namespace Xxam\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExtjsstateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtjsstateRepository extends EntityRepository
{
    
    
}
