<?php

namespace Xxam\DynmodBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DatacontainerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DatacontainerRepository extends EntityRepository
{
}
