<?php

namespace Xxam\DynmodBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FormdefinitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FormdefinitionRepository extends EntityRepository
{
}
