services:
#    xxam_core.example:
#        class: Xxam\CalendarBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    xxamcalendarbundle.menuservice:
        class: Xxam\CalendarBundle\Services\MenuService
        # arguments: ["@templating"]
        arguments: ["@security.token_storage"]
        tags:
            -  { name: xxam.menuservice }
    xxamcalendarbundle.rolesservice:
        class: Xxam\CalendarBundle\Services\RolesService
        # arguments: ["@templating"]
        arguments: ["@security.token_storage"]
        tags:
            -  { name: xxam.rolesservice }