xxam_comm:
    resource: "@XxamCommBundle/Resources/config/routing.yml"
    prefix:   /



xxam_contact:
    resource: "@XxamContactBundle/Resources/config/routing.yml"
    prefix:   /

xxam_core:
    resource: "@XxamCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
xxam_emailclient:
    resource: "@XxamMailclientBundle/Resources/config/routing.yml"
    prefix:   /
    
xxam_calendar:
    resource: "@XxamCalendarBundle/Resources/config/routing.yml"
    prefix:   /
    
xxam_coding:
    resource: "@XxamCodingBundle/Resources/config/routing.yml"
    prefix:   /
    
xxam_filemanager:
    resource: "@XxamFilemanagerBundle/Resources/config/routing.yml"
    prefix:   /
    
xxam_user:
    resource: "@XxamUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#fos_user_group:
#    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
#    prefix: /group
    
#Just\ThumbnailBundle\Controller
xxam_thumbnail:
    path:  /thumbnails/{mode}/{maxx}x{maxy}/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        #maxy: ~
        img: ".+"

xxam_thumbnail_x:
    path:  /thumbnails/{mode}/{maxx}x/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxx: ~
        img: ".+"

xxam_thumbnail_y:
    path:  /thumbnails/{mode}/x{maxy}/{img}
    defaults: { _controller: JustThumbnailBundle:Thumbnail:thumbnail }
    requirements:
        #mode: ~
        #maxy: ~
        img: ".+"

create:
    resource: "@CmfCreateBundle/Resources/config/routing/rest.xml"

#create_image:
#    resource: "@CmfCreateBundle/Resources/config/routing/image.xml"