services:
#    xxam_core.example:
#        class: XxamMailclientBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]


#    xxamportalwidget.mailclient.mails:
#        class: XxamMailclientBundle\Controller\MailsWidgetController
#        tags:
#            -  { name: xxamportalwidget }

    #every portal-widget must start with "xxamportalwidget...."
    xxamportalwidget.mailclient.newmails:
        class: XxamMailclientBundle\Controller\NewmailsWidgetController
        arguments: ["@templating", "@security.token_storage"]
        tags:
            -  { name: xxamportalwidget }