parameters:
    fileextensionswiththumbnails: ["jpg", "jpeg", "png", "tiff", "tif", "gif", "bmp", "webp", "wbmp"]
    fileextensiontomimetype:
        "epub": "application-epub+zip.png"
        "ai": "application-illustrator.png"
        "js": "application-javascript.png"
        "dotx": "application-msword-template.png"
        "dot": "application-msword-template.png"
        "docx": "application-msword.png"
        "doc": "application-msword.png"
        "empty": "application-octet-stream.png"
        "pdf": "application-pdf.png"
        #"pgp": "application-pgp-encrypted.png"
        "pgp": "application-pgp-keys.png"
        "p7b": "application-pkcs7-mime.png"
        "ps": "application-postscript.png"
        "rng": "application-relaxng.png"
        "rss": "application-rss+xml.png"
        "rtf": "application-rtf.png"
        "sxw": "application-sxw.png"
        "kml": "application-vnd-google-earth-kml.png"
        "icc": "application-vnd.iccprofile.png"
        "mdb": "application-vnd.ms-access.png"
        "accdb": "application-vnd.ms-access.png"
        "xls": "application-vnd.ms-excel.png"
        "xlsx": "application-vnd.ms-excel.png"
        "ppt": "application-vnd.ms-powerpoint.png"
        "pptx": "application-vnd.ms-powerpoint.png"
        "odc": "application-vnd.oasis.opendocument.chart.png"
        "odd": "application-vnd.oasis.opendocument.database.png"
        ".odft": "application-vnd.oasis.opendocument.formula-template.png"
        "odf": "application-vnd.oasis.opendocument.formula.png"
        "odg": "application-vnd.oasis.opendocument.graphics.png"
        "odi": "application-vnd.oasis.opendocument.image.png"
        "otp": "application-vnd.oasis.opendocument.presentation-template.png"
        "odp": "application-vnd.oasis.opendocument.presentation.png"
        "ots": "application-vnd.oasis.opendocument.spreadsheet-template.png"
        "ods": "application-vnd.oasis.opendocument.spreadsheet.png"
        "odm": "application-vnd.oasis.opendocument.text-master.png"
        "ott": "application-vnd.oasis.opendocument.text-template.png"
        "odt": "application-vnd.oasis.opendocument.text.png"
        "docx": "application-vnd.openxmlformats-officedocument.wordprocessingml.document.png"
        "rm": "application-vnd.rn-realmedia.png"
        #"": "application-vnd.scribus.png"
        "sdc": "application-vnd.stardivision.calc.png"
        "sda": "application-vnd.stardivision.draw.png"
        #"": "application-vnd.stardivision.mail.png"
        "smf": "application-vnd.stardivision.math.png"
        "sdc": "application-vnd.sun.xml.calc.png"
        #"": "application-vnd.sun.xml.calc.template.png"
        "sxd": "application-vnd.sun.xml.draw.png"
        "std": "application-vnd.sun.xml.draw.template.png"
        "sxi": "application-vnd.sun.xml.impress.png"
        "sti": "application-vnd.sun.xml.impress.template.png"
        "sxm": "application-vnd.sun.xml.math.png"
        "sxg": "application-vnd.sun.xml.writer.global.png"
        "sxw": "application-vnd.sun.xml.writer.png"
        "stw": "application-vnd.sun.xml.writer.template.png"
        "wpd": "application-vnd.wordperfect.png"
        "7z": "application-x-7z-compressed.png"
        "abw": "application-x-abiword.png"
        "ace": "application-x-ace.png"
        #"": "application-x-applix-spreadsheet.png"
        #"": "application-x-applix-word.png"
        #"": "application-x-ar.png"
        #"": "application-x-arc.png"
        #"": "application-x-archive.png"
        #"": "application-x-arj.png"
        #"": "application-x-awk.png"
        "torrent": "application-x-bittorrent.png"
        #"": "application-x-blender.png"
        #"": "application-x-bzdvi.png"
        #"": "application-x-bzip-compressed-tar.png"
        "bz": "application-x-bzip.png"
        #"": "application-x-cd-image.png"
        #"": "application-x-cda.png"
        #"": "application-x-chm.png"
        #"": "application-x-compress.png"
        "tgz": "application-x-compressed-tar.png"
        "cpio": "application-x-cpio.png"
        #"": "application-x-cue.png"
        "deb": "application-x-deb.png"
        #"": "application-x-designer.png"
        #"": "application-x-desktop.png"
        #"": "application-x-dgn.png"
        #"": "application-x-egon.png"
        #"": "application-x-executable-script.png"
        #"": "application-x-executable.png"
        "afm": "application-x-font-afm.png"
        "bdf": "application-x-font-bdf.png"
        "otf": "application-x-font-otf.png"
        "pcf": "application-x-font-pcf.png"
        "snf": "application-x-font-snf.png"
        "ttf": "application-x-font-ttf.png"
        "type1": "application-x-font-type1.png"
        "gnumeric": "application-x-gnumeric.png"
        "gzdvi": "application-x-gzdvi.png"
        "gzip": "application-x-gzip.png"
        #"": "application-x-gzpostscript.png"
        "it87": "application-x-it87.png"
        #"": "application-x-java-applet.png"
        "jar": "application-x-java-archive.png"
        #"": "application-x-java.png"
        "js": "application-x-javascript.png"
        "k3b": "application-x-k3b.png"
        "kcsrc": "application-x-kcsrc.png"
        #"": "application-x-kexi-connectiondata.png"
        #"": "application-x-kexiproject-shortcut.png"
        #"": "application-x-kexiproject-sqlite.png"
        #"": "application-x-kexiproject-sqlite2.png"
        #"": "application-x-kexiproject-sqlite3.png"
        "kfo": "application-x-kformula.png"
        #"": "application-x-kgetlist.png"
        "kon": "application-x-kontour.png"
        #"": "application-x-kplato.png"
        #"": "application-x-krita.png"
        #"": "application-x-kvtml.png"
        "kwd": "application-x-kword.png"
        "lha": "application-x-lha.png"
        "lyx": "application-x-lyx.png"
        #"": "application-x-lzma-compressed-tar.png"
        #"": "application-x-lzop.png"
        "m4": "application-x-m4.png"
        #"": "application-x-marble.png"
        #"": "application-x-mimearchive.png"
        #"": "application-x-mplayer2.png"
        "com": "application-x-ms-dos-executable.png"
        #"": "application-x-mswinurl.png"
        "wri": "application-x-mswrite.png"
        "nzb": "application-x-nzb.png"
        "object": "application-x-object.png"
        "pak": "application-x-pak.png"
        "pem": "application-x-pem-key.png"
        "perl": "application-x-perl.png"
        "php": "application-x-php.png"
        #"": "application-x-plasma.png"
        #"": "application-x-python-bytecode.png"
        #"": "application-x-qet-element.png"
        #"": "application-x-qet-project.png"
        #"": "application-x-quattropro.png"
        "rar": "application-x-rar.png"
        "rpm": "application-x-rpm.png"
        "ruby": "application-x-ruby.png"
        #"": "application-x-sharedlib.png"
        "sh": "application-x-shellscript.png"
        "swf": "application-x-shockwave-flash.png"
        "siag": "application-x-siag.png"
        #"": "application-x-smb-server.png"
        #"": "application-x-smb-workgroup.png"
        #"": "application-x-sqlite2.png"
        #"": "application-x-sqlite3.png"
        "srt": "application-x-srt.png"
        #"": "application-x-srtrip.png"
        #"": "application-x-subrip.png"
        "tar": "application-x-tar.png"
        #"": "application-x-tarz.png"
        #"": "application-x-tgif.png"
        #"": "application-x-trash.png"
        "t": "application-x-troff-man.png"
        "tzo": "application-x-tzo.png"
        "wmf": "application-x-wmf.png"
        #"": "application-x-zerosize.png"
        "zoo": "application-x-zoo.png"
        "xhtml": "application-xhtml+xml.png"
        "xml": "application-xml.png"
        "xsd": "application-xsd.png"
        "xslt": "application-xslt+xml.png"
        "zip": "application-zip.png"
        "ac3": "audio-ac3.png"
        "mid": "audio-midi.png"
        #"": "audio-prs.sid.png"
        "rm": "audio-vn.rn-realmedia.png"
        "rv": "audio-vn.rn-realvideo.png"
        #"": "audio-vnd.rn-realvideo.png"
        "adp": "audio-x-adpcm.png"
        "aif": "audio-x-aiff.png"
        "ogg": "audio-x-flac+ogg.png"
        #"": "audio-x-flac.png"
        #"": "audio-x-generic.png"
        #"": "audio-x-monkey.png"
        #"": "audio-x-speex+ogg.png"
        "wav": "audio-x-wav.png"
        #"": "image-svg+xml-compressed.png"
        "svg": "image-svg+xml.png"
        "dwg": "image-vnd.dwg.png"
        "dng": "image-x-adobe-dng.png"
        "eps": "image-x-eps.png"
        "jpg": "image-x-generic.png"
        "jpeg": "image-x-generic.png"
        "gif": "image-x-generic.png"
        "png": "image-x-generic.png"
        #"": "image-x-vnd.trolltech.qpicture.png"
        "fig": "image-x-xfig.png"
        #"": "inode-directory.png"
        #"": "message-news.png"
        #"": "message-partial.png"
        #"": "message-rfc822.png"
        #"": "message-x-gnu-rmail.png"
        #"": "message.png"
        #"": "package-x-generic.png"
        "ics": "text-calendar.png"
        "css": "text-css.png"
        "csv": "text-csv.png"
        #"": "text-directory.png"
        #"": "text-enriched.png"
        "html": "text-html.png"
        "mathml": "text-mathml.png"
        "txt": "text-plain.png"
        "rdf": "text-rdf+xml.png"
        #"": "text-rdf.png"
        "rtf": "text-rtf.png"
        "sgml": "text-sgml.png"
        "troff": "text-troff.png"
        "vcs": "text-vcalendar.png"
        "abc": "text-vnd.abc.png"
        "wml": "text-vnd.wap.wml.png"
        "adasrc": "text-x-adasrc.png"
        "authors": "text-x-authors.png"
        "bibtex": "text-x-bibtex.png"
        "hdr": "text-x-c++hdr.png"
        "src": "text-x-c++src.png"
        "changelog": "text-x-changelog.png"
        "chdr": "text-x-chdr.png"
        "cmake": "text-x-cmake.png"
        "copying": "text-x-copying.png"
        "csharp": "text-x-csharp.png"
        "csrc": "text-x-csrc.png"
        "dtd": "text-x-dtd.png"
        "generic": "text-x-generic.png"
        "haskell": "text-x-haskell.png"
        "hex": "text-x-hex.png"
        "install": "text-x-install.png"
        "java": "text-x-java.png"
        "katefilelist": "text-x-katefilelist.png"
        "ldif": "text-x-ldif.png"
        "lilypond": "text-x-lilypond.png"
        "log": "text-x-log.png"
        "makefile": "text-x-makefile.png"
        "nfo": "text-x-nfo.png"
        "objchdr": "text-x-objchdr.png"
        "objcsrc": "text-x-objcsrc.png"
        "pascal": "text-x-pascal.png"
        "patch": "text-x-patch.png"
        "po": "text-x-po.png"
        "python": "text-x-python.png"
        "qml": "text-x-qml.png"
        "readme": "text-x-readme.png"
        "rpm-spec": "text-x-rpm-spec.png"
        "script": "text-x-script.png"
        "sql": "text-x-sql.png"
        "tcl": "text-x-tcl.png"
        "tex": "text-x-tex.png"
        "texinfo": "text-x-texinfo.png"
        "vcard": "text-x-vcard.png"
        "xslfo": "text-x-xslfo.png"
        "xmcd": "text-xmcd.png"
        "xml": "text-xml.png"
        "unknown": "unknown.png"
        #"": "uri-mms.png"
        #"": "uri-mmst.png"
        #"": "uri-mmsu.png"
        #"": "uri-pnm.png"
        #"": "uri-rtspt.png"
        #"": "uri-rtspu.png"
        #"": "video-x-generic.png"
        "mng": "video-x-mng.png"
        #"": "x-kde-nsplugin-generated.png"
        "podcast": "x-media-podcast.png"
        #"": "x-office-address-book.png"
        #"": "x-office-calendar.png"
        #"": "x-office-document.png"
        #"": "x-office-presentation.png"
        #"": "x-office-spreadsheet.png"

    