just_admin_homepage:
    path:     /
    defaults: { _controller: JustAdminBundle:Default:index }
    
just_admin_portal:
    path:     /portal
    defaults: { _controller: JustAdminBundle:Default:portal }
    
just_admin_getwidget:
    path:     /portal/getwidget/{id}
    defaults: { _controller: JustAdminBundle:Default:getwidget }
    
just_admin_addwidget:
    path:     /portal/addwidget
    defaults: { _controller: JustAdminBundle:Default:addwidget }
    
just_admin_doaddwidget:
    path:     /portal/doaddwidget
    defaults: { _controller: JustAdminBundle:Default:doaddwidget }
    
just_admin_getwidgets:
    path:     /portal/getwidgets
    defaults: { _controller: JustAdminBundle:Default:getwidgets }
    
just_admin_removewidget:
    path:     /portal/removewidget/{id}
    defaults: { _controller: JustAdminBundle:Default:removewidget }    

    
just_admin_feedwidget_loadfeed:
    path:     /portal/feedwidget/loadfeed/{url}
    defaults: { _controller: JustAdminBundle:FeedWidget:loadfeed }
    
just_admin_statefulservice:
    path:     /statefulservice
    defaults: { _controller: JustAdminBundle:Default:statefulservice }


uploadfileprogress:
    path: /uploadfileprogress
    defaults: { _controller: JustAdminBundle:Default:uploadfileprogress }