imports:
    - { resource: parameters.yml }
services:
#    xxam_core.example:
#        class: Xxam\HelpBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    xxamhelpbundle.menuservice:
        class: Xxam\HelpBundle\Services\MenuService
        # arguments: ["@templating"]
        arguments: ["@security.token_storage"]
        tags:
            -  { name: xxam.menuservice }

    xxamhelpbundle.rolesservice:
       class: Xxam\HelpBundle\Services\RolesService
       tags:
           -  { name: xxam.rolesservice }