imports:
    - { resource: parameters.yml }
services:
#    xxam_core.example:
#        class: Xxam\ContactBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    xxamcontactbundle.menuservice:
        class: Xxam\ContactBundle\Services\MenuService
        # arguments: ["@templating"]
        arguments: ["@security.token_storage"]
        tags:
            -  { name: xxam.menuservice }
    xxamcontactbundle.rolesservice:
       class: Xxam\ContactBundle\Services\RolesService
       tags:
           -  { name: xxam.rolesservice }