xxam_dynmod:
    resource: "@XxamDynmodBundle/Controller/DynmodController.php"
    type: annotation

xxam_dynmod_api:
    resource: "@XxamDynmodBundle/Controller/DynmodRESTController.php"
    type:   rest
    prefix:   /api

xxam_dynmod_datacontainer:
    resource: "@XxamDynmodBundle/Controller/DatacontainerController.php"
    type: annotation

xxam_dynmod_datacontainer_api:
    resource: "@XxamDynmodBundle/Controller/DatacontainerRESTController.php"
    type:   rest
    prefix:   /api