imports:
    - { resource: parameters.yml }
services:
#    xxam_core.example:
#        class: Xxam\DynmodBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    xxamdynmodbundle.menuservice:
        class: Xxam\DynmodBundle\Services\MenuService
        # arguments: ["@templating"]
        arguments: ["@security.token_storage","@doctrine.orm.entity_manager"]
        tags:
            -  { name: xxam.menuservice }

    xxamdynmodbundle.rolesservice:
       class: Xxam\DynmodBundle\Services\RolesService
       tags:
           -  { name: xxam.rolesservice }
       arguments:
        entityManager: "@doctrine.orm.entity_manager"