parameters:
  filesystemadapters:
    local: 
        path: 
            type: text
            help: The root path
        links:
            type: select
            values:
                DISALLOW_LINKS: Disallow
                SKIP_LINKS: Skip
            help: The Local adapter doesn’t support links, this violates the root path constraint which is enforces throughout Flysystem. By default, when links are encountered an exception is thrown.
        cache:
            type: checkbox
            help: Use Memcached to cache file system meta-data to boost performance. 
    dropbox:
        prefix:
            type: text
            help: The root path
        access_token:
            type: text
            help: Visit https://www.dropbox.com/developers/apps and get your “App secret”.
        app_secret:
            type: text
            help: Use Memcached to cache file system meta-data to boost performance. 
    ftp:
        host:
            type: text
            help: The server domain or IP
        username:
            type: text
            help: The FTP-Username
        password:
            type: password
            help: The FTP-Password
        port:
            type: number
            default: 21
            help: The FTP-Port
        root:
            type: text
            help: The root path
        passive:
            type: checkbox
            help: Use FTP passive mode
        ssl:
            type: checkbox
            help: Use SSL
        timeout:
            type: number
            default: 30
            help: Connection timeout in seconds
    sftp:
        host:
            type: text
            help: The server domain or IP
        username:
            type: text
            help: The SFTP-Username
        password:
            type: password
            help: The SFTP-Password
        port:
            type: number
            default: 21
            help: The FTP-Port
        root:
            type: text
            help: The root path
        privateKey:
            type: text
            help: Path to private key on server
        timeout:
            type: number
            default: 30
            help: Connection timeout in seconds
        
