filemanager:
    path: /filemanager
    defaults: { _controller: JustFilemanagerBundle:Filemanager:index }

filemanager_listfolders:
    path: /filemanager/listfolders
    defaults: { _controller: JustFilemanagerBundle:Filemanager:listfolders }

filemanager_listfiles:
    path: /filemanager/listfiles
    defaults: { _controller: JustFilemanagerBundle:Filemanager:listfiles }

filemanager_deletefile:
    path: /filemanager/deletefile
    defaults: { _controller: JustFilemanagerBundle:Filemanager:deletefile }
     
filemanager_movefile:
    path: /filemanager/movefile
    defaults: { _controller: JustFilemanagerBundle:Filemanager:movefile }    
    
filemanager_copyfile:
    path: /filemanager/copyfile
    defaults: { _controller: JustFilemanagerBundle:Filemanager:copyfile }  
    
filemanager_writefile:
    path: /filemanager/writefile
    defaults: { _controller: JustFilemanagerBundle:Filemanager:writefile }
    
filemanager_readfile:
    path: /filemanager/readfile
    defaults: { _controller: JustFilemanagerBundle:Filemanager:readfile }
    
    
    
    
    
filemanager_admin:
    path: /filemanager/admin
    defaults: { _controller: JustFilemanagerBundle:Filemanager:admin }
    
filemanager_new:
    path: /filemanager/edit
    defaults: { _controller: JustFilemanagerBundle:Filemanager:new }

filemanager_edit:
    path: /filemanager/edit/{id}
    defaults: { _controller: JustFilemanagerBundle:Filemanager:edit }

filemanager_getthumbnail:
    path: /filemanager/getthumbnail
    defaults: { _controller: JustFilemanagerBundle:Filemanager:getThumbnail }
    
just_filemanager_filemanager_api:
    resource: "@JustFilemanagerBundle/Controller/FilemanagerRESTController.php"
    type:   rest
    prefix:   /api