<?php

namespace Xxam\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommunicationdataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunicationdataRepository extends EntityRepository
{

}
