<?php

namespace Xxam\MailclientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MailspoolRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class MailspoolRepository extends EntityRepository
{
    public function getTotalcount($filters){
        $query = $this->createQueryBuilder('e');
        $query->select('COUNT(DISTINCT e.id)');
        $z=0;
        foreach($filters as $key => $value){
            $query->andWhere('(e.'.$key.' = :value'.$z);
            $query->setParameter('value'.$z, $value);
        }
        return $query->getQuery()->getSingleScalarResult();
    }
    public function getModelFields(){
        $fields=Array();
        $fields[]=Array('name'=> 'id','type'=>'int');
        $fields[]=Array('name'=> 'mailaccount_id','type'=>'int');
        $fields[]=Array('name'=> 'user_id','type'=>'int');
        $fields[]=Array('name'=> 'subject','type'=>'string');
        $fields[]=Array('name'=> 'emailto','type'=>'string');
        $fields[]=Array('name'=> 'sendafter','type'=>'date', 'dateFormat'=>'Y-m-d H:i:s');
        $fields[]=Array('name'=> 'sendtime','type'=>'date', 'dateFormat'=>'Y-m-d H:i:s');
        $fields[]=Array('name'=> 'readtimes','type'=>'string');
        $fields[]=Array('name'=> 'sendstatus','type'=>'int');
        $fields[]=Array('name'=> 'created','type'=>'date', 'dateFormat'=>'Y-m-d H:i:s');
        $fields[]=Array('name'=> 'updated','type'=>'date', 'dateFormat'=>'Y-m-d H:i:s');
        return $fields;

    }
    public function getGridColumns(){
        $columns=Array();
        $columns[]=Array('text'=> 'Id','dataIndex'=> 'id', 'filter'=> Array('type'=> 'number'),'hidden'=> true);
        $columns[]=Array('text'=> 'Subject','flex'=> 1,'dataIndex'=> 'subject', 'filter'=> Array('type'=> 'string'));
        $columns[]=Array('text'=> 'To','flex'=> 1,'dataIndex'=> 'emailto', 'filter'=> Array('type'=> 'string'));
        $columns[]=Array('text'=> 'Send after','dataIndex'=> 'sendafter', 'xtype'=> 'datecolumn', 'format'=>'Y-m-d H:i:s', 'filter'=> Array('type'=> 'date'),'hidden'=> false);
        $columns[]=Array('text'=> 'Send time','dataIndex'=> 'sendtime', 'xtype'=> 'datecolumn', 'format'=>'Y-m-d H:i:s', 'filter'=> Array('type'=> 'date'),'hidden'=> false);
        $columns[]=Array('text'=> 'Read times','dataIndex'=> 'readtimes', 'hidden'=> false);
        $columns[]=Array('text'=> 'Sendstatus','dataIndex'=> 'sendstatus', 'filter'=> Array('type'=> 'number'),'hidden'=> false);
        $columns[]=Array('text'=> 'Created','dataIndex'=> 'created', 'xtype'=> 'datecolumn', 'format'=>'Y-m-d H:i:s', 'filter'=> Array('type'=> 'date'),'hidden'=> true);
        $columns[]=Array('text'=> 'Updated','dataIndex'=> 'updated', 'xtype'=> 'datecolumn', 'format'=>'Y-m-d H:i:s', 'filter'=> Array('type'=> 'date'),'hidden'=> true);
        return $columns;

    }
}
